name: Build, test, and push to Google Artifact Repository

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  REGISTRY: us-central1-docker.pkg.dev
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - id: auth
      name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        token_format: access_token
        workload_identity_provider: projects/109844845926/locations/global/workloadIdentityPools/holo-wtf-api-pool/providers/holo-wtf-api-provider
        service_account: github-actions-service-account@holo-wtf-api-376303.iam.gserviceaccount.com

    - name: Log in to the Artifact repository
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: 'oauth2accesstoken'
        password: ${{ steps.auth.outputs.access_token }}

    - name: Build and push Docker image
      uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
      with:
        context: .
        push: true
        tags: us-central1-docker.pkg.dev/holo-wtf-api-376303/holo-wtf-api/holo-wtf-api:latest
     
    - id: 'deploy'
      name: Deploy to Google Cloud Run
      uses: 'google-github-actions/deploy-cloudrun@v1'
      with:
        service: 'holo-wtf-api'
        image: 'us-central1-docker.pkg.dev/holo-wtf-api-376303/holo-wtf-api/holo-wtf-api:latest'
